project_id = "getyvjzfjvuzeflxoksq"

[functions.chat]
verify_jwt = false

[functions.generate-image]
verify_jwt = false

[functions.image-to-image]
verify_jwt = false

[functions.pexels-videos]
verify_jwt = false

[functions.generate-video-script]
verify_jwt = false

[functions.google-tts]
verify_jwt = false

[functions.video-editor]
verify_jwt = false

[functions.video-render]
verify_jwt = false
